### ISSUE TITLE
Relicense 02-html-full as CC0?

### ISSUE THREAD

**Issue by stain** [a2a-fair-metrics/a2a-fair-metrics#14]
@wilkos-dans --  is it possible to re-license [02-html-full](https://w3id.org/a2a-fair-metrics/02-html-full/) to CC0 license? I am not sure who is the copyright holder as you adapted it from a previous example?

I've included a cache of 02-html-full in the [unit tests for signposting.py](https://github.com/stain/signposting/tree/main/tests/data/a2a-fair-metrics) but this raised a few challenges:

* The CC-BY license require I attribute authors -- so I modified [LICENSE](https://github.com/stain/signposting/blob/main/LICENSE#L205) however the file says the author is Josiah Carberry (the example ORCID) -- so this is misleading
* I am unable to modify the HTML without also adding notification of changes. For instance I wanted to remove the `schema.DC` bits that are not related to signposting. 

Apache Software Foundation considers CC-BY as a [Category B](https://www.apache.org/legal/resolved.html#cc-by) license - that "maybe" included. This is mainly due to CC-BY having anti-DRM measures. This is generally a good idea for AV media, but for this HTML test it means a theoretical DRM-Signposting library based on signposting.py may need to delete 02-html-full. Such "restrictions on use" are counter to open source licenses like Apache License and GPL.

**Comment by wilkos-dans** [comment]
Hi @stain, Yes, I think we can. The license is meant as an implementation example, so imho we can change this to whatever suits us. if CC0 is more practical than we'll use that, or apache-2. Also the author mentioned is not the author of the file I took as an example. I think we will need to change this author to a non-extisting person? I dont think we need to mention the 'previous' example copyright holder, for this is just an implementation of open standards? Anyone will come up with this result in the end and it it licensed [CC0 1.0 Universal](https://github.com/borsna/fair-examples/blob/main/LICENSE). I'd be happy to make the changes in the 02-full-example. Should I do that in this repository? The LICENSE file and the accompanying json should then also be edited, I guess?

**Comment by stain** [comment]
Hi, @wilkos-dans -- are you able to propose the above change to this example, or should we have a go at the a2a hackathon tomorrow?

**Comment by wilkos-dans** [comment]
Hi @stain , I am not really into licensing. But what I understand from you until now, is that the given ORCID of the fictitious person, is not appropriate under the proposed CC0 license? If so, we can change the name/orcid to mine for instance?
What about the org_id/ROR, which is an (arbitrary) existing institute? Should we also use another ROR then? Like DANS' ROR? https://ror.org/008pnp284
